### ISSUE TITLE
Setup database storage for offline mutations 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-android#6]
**TODO** - needs more details

# Motivation

Once application stops all in memory items will be removed. 
To persist all the offline items after restarts we need to persist them in local database

# Suggested approach

Create pojo object that will map optimistic response and offline data:

```java
private Map<String, String> optimisticResponse;
Operation<PersistedCacheObject> graphqlOperation;
```

# Tasks

- [x] Reasearch how to store offline data in database
- [x] Provide provide interface for saving and retrieving queue
- [ ] Refuel queue on application restart. 
- [ ] Reapply optimistic responses on application restart.
